#!/usr/bin/env node
// Copies the icons and file name rules of Starlight's <FileTree> into the package: `node scripts/file-icons.mjs`.
// Starlight does not export them, so the package keeps its own copy. `test/file-icons.test.ts` checks it for drift.
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const pkg = join(root, 'packages/starlight-codeblocks');
const starlight = join(pkg, 'node_modules/@astrojs/starlight/dist');
const { definitions } = await import(pathToFileURL(join(starlight, 'user-components/file-tree-icons.js')).href);
const { Icons } = await import(pathToFileURL(join(starlight, 'components-internals/Icons.js')).href);

const names = new Set([
  'seti:default',
  ...Object.values(definitions.files),
  ...Object.values(definitions.extensions),
  ...Object.values(definitions.partials),
  ...Object.keys(Icons).filter((name) => name.startsWith('seti:')),
]);
const icons = Object.fromEntries([...names].sort().map((name) => [name, Icons[name]]));

const licence = readFileSync(join(starlight, 'user-components/file-tree-icons.js'), 'utf8').match(
  /\/\*\*[\s\S]*?\*\//,
)[0];
const out = join(pkg, 'src/expressive-code/file-icons-data.ts');
writeFileSync(
  out,
  `// Generated by scripts/file-icons.mjs from @astrojs/starlight. Do not edit.
${licence.replace(/^\*/gm, ' *')}
export const definitions: {
  files: Record<string, string>;
  extensions: Record<string, string>;
  partials: Record<string, string>;
} = ${JSON.stringify(definitions)};

/** The inner SVG of each 24 by 24 icon, by its Starlight name. */
export const icons: Record<string, string> = ${JSON.stringify(icons)};
`,
);
execFileSync('pnpm', ['exec', 'biome', 'format', '--write', out], { cwd: root, stdio: 'inherit' });
