#!/usr/bin/env node
// Copies the file name rules of the coloured icon sets into the package: `node scripts/icon-sets.mjs`.
// The rules come from each VS Code icon theme. The icons stay in the `@iconify-json/*` packages, which sites
// install for the set they choose. Rules for icons that the installed Iconify package lacks are left out.
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const pkg = join(root, 'packages/starlight-codeblocks');
const modules = join(pkg, 'node_modules');
const json = (path) => JSON.parse(readFileSync(path, 'utf8'));

/** The icon theme manifest of a VS Code extension on Open VSX, at a fixed version. */
function vsix(extension, version, manifest) {
  const dir = mkdtempSync(join(tmpdir(), 'scb-vsix-'));
  const [namespace, name] = extension.split('/');
  const url = `https://open-vsx.org/api/${namespace}/${name}/${version}/file/${namespace}.${name}-${version}.vsix`;
  execFileSync('curl', ['-sfL', '-o', join(dir, 'x.vsix'), url]);
  execFileSync('unzip', ['-q', join(dir, 'x.vsix'), `extension/${manifest}`, '-d', dir]);
  return json(join(dir, 'extension', manifest));
}

const sets = [
  {
    id: 'material',
    source: `material-icon-theme ${json(join(modules, 'material-icon-theme/package.json')).version}`,
    manifest: json(join(modules, 'material-icon-theme/dist/material-icons.json')),
    iconify: 'material-icon-theme',
    renames: { file: 'document' },
    light: (name) => `${name}-light`,
  },
  {
    id: 'vscode-icons',
    source: 'vscode-icons 13.0.0',
    manifest: vsix('vscode-icons-team/vscode-icons', '13.0.0', 'dist/src/vsicons-icon-theme.json'),
    iconify: 'vscode-icons',
    light: (name) => name.replace(/^file-type-/, 'file-type-light-'),
  },
  {
    id: 'catppuccin',
    source: 'catppuccin-vsc-icons 1.26.0',
    manifest: vsix('Catppuccin/catppuccin-vsc-icons', '1.26.0', 'dist/macchiato/theme.json'),
    iconify: 'catppuccin',
  },
];

// The Iconify Catppuccin icons use the Macchiato colours. Light themes get the same colour from Latte.
const { flavors } = await import(join(modules, '@catppuccin/palette/esm/mod.js'));
const palette = Object.fromEntries(
  Object.entries(flavors.macchiato.colors).map(([name, colour]) => [colour.hex, flavors.latte.colors[name].hex]),
);

for (const set of sets) {
  const { icons, aliases = {} } = json(join(modules, `@iconify-json/${set.iconify}/icons.json`));
  const has = (name) => name in icons || name in aliases;
  const iconName = (id) => {
    const path = set.manifest.iconDefinitions[id]?.iconPath;
    if (!path) return undefined;
    const name = path
      .split('/')
      .at(-1)
      .replace(/\.svg$/, '')
      .replace(/^_+/, '')
      .replaceAll('_', '-');
    const renamed = set.renames?.[name] ?? name;
    return has(renamed) ? renamed : undefined;
  };
  const table = (record = {}) =>
    Object.fromEntries(
      Object.entries(record)
        .map(([key, id]) => [key.toLowerCase(), iconName(id)])
        .filter(([, name]) => name)
        .sort(([a], [b]) => (a < b ? -1 : 1)),
    );
  const rules = {
    fileNames: table(set.manifest.fileNames),
    fileExtensions: table(set.manifest.fileExtensions),
    languageIds: table(set.manifest.languageIds),
    file: iconName(set.manifest.file),
  };
  const used = new Set([
    rules.file,
    ...Object.values(rules.fileNames),
    ...Object.values(rules.fileExtensions),
    ...Object.values(rules.languageIds),
  ]);
  const light = set.light
    ? Object.fromEntries(
        [...used]
          .sort()
          .map((name) => [name, set.light(name)])
          .filter(([name, variant]) => variant !== name && has(variant)),
      )
    : {};
  const out = join(pkg, `src/expressive-code/icon-sets/${set.id}.ts`);
  writeFileSync(
    out,
    `// Generated by scripts/icon-sets.mjs from ${set.source}, for @iconify-json/${set.iconify}. Do not edit.
import type { IconSetRules } from './types.ts';

export const rules: IconSetRules = ${JSON.stringify({ ...rules, light, ...(set.id === 'catppuccin' && { palette }) })};
`,
  );
  execFileSync('pnpm', ['exec', 'biome', 'format', '--write', out], { cwd: root, stdio: 'ignore' });
  console.log(
    set.id,
    Object.keys(rules.fileNames).length,
    Object.keys(rules.fileExtensions).length,
    Object.keys(light).length,
  );
}
